services:
  redmine:
    image: akozma056/redmine_app:latest #if image exists, use it
    build: #otherwise build it
      context: .
      args:
        REDMINE_VERSION: ${REDMINE_VERSION}
    container_name: redmine_app
    restart: unless-stopped
    ports:
      - "${REDMINE_PORT}:3000"
    
    user: "999:999"
    environment:
      REDMINE_DB_POSTGRES: ${REDMINE_DB_POSTGRES}
      REDMINE_DB_USERNAME: ${POSTGRES_USER}
      REDMINE_DB_PASSWORD: ${POSTGRES_PASSWORD}
      REDMINE_DB_DATABASE: ${POSTGRES_DB}
      REDMINE_SECRET_KEY_BASE: ${REDMINE_SECRET_KEY_BASE}
      REDMINE_SMTP_HOST: "smtp.office365.com"
      REDMINE_SMTP_PORT: "587"
      REDMINE_SMTP_USERNAME: ${SMTP_USER}
      REDMINE_SMTP_PASSWORD: ${SMTP_PASS}
      REDMINE_SMTP_DOMAIN: ${SMTP_DOMAIN}
      REDMINE_SMTP_AUTHENTICATION: "login"
      REDMINE_SMTP_ENABLE_STARTTLS_AUTO: "true"
      
    volumes:
      - ./data/files:/usr/src/redmine/files
    depends_on:
      - db

  db:
    image: postgres:${POSTGRES_VERSION}
    container_name: redmine_db
    user: "999:999"
    restart: unless-stopped
    command: postgres -c "datestyle=ISO,MDY"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./data/postgresql:/var/lib/postgresql/data
    shm_size: 256mb

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_POLL_INTERVAL=300
    restart: unless-stopped

  backup:
    image: akozma056/redmine_backup:latest
    container_name: backup_bot
    depends_on:
      - db
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    restart: unless-stopped
